### ISSUE TITLE
Research on necessary endpoints for saving homework

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor-bot#133]
We have such task in our semester's plan:

![image](https://github.com/fictadvisor/fictadvisor-bot/assets/42845566/106f3ba9-6b3e-4a49-911f-ed79aa2262ac)

What does it mean?

We don't have in database such field as "homework". Homework is a description (eventInfo) for exact event of lesson. We need to have an ability to save this event info from bot.

Functionality:
- Save new info into event of this week lesson event or next event of the lesson's sequence, command in DM and Group chat (captain and moderator)
- Edit info of event of this week lesson event or next event of the lesson's sequence, command in DM and Group chat (captain and moderator)
- Delete info of event of this week lesson event or next event of the lesson's sequence, command in DM and Group chat (captain and moderator)
- Show the list of events infos for today, command in DM and Group chat
- Show the list of events infos for next day, command in DM and Group chat
- Show the list of events infos for current week, command in DM and Group chat
- Show the list of events infos for next week, command in DM and Group chat
- Show the list of events infos for exact lesson's event sequence, command in DM and Group chat

**The task is to say what endpoints and tables in database should back-end have. It must be fully described with essential requests, responses, fields, queries, data types, etc.**

**Comment by ke1wi** [comment]
To implement the described functionality, we would need those tables and endpoint with those responses.
---

### Database Tables:

1.  **Events Table:**
	    - `event_id` (PK)
	    - `disciplineId`: `"string"`
	    - `disciplineType`: `enum "LECTURE|LAB|PRACTICE"`
		- `start_time`: `"DATETIME"`
		- `end_time`: `"DATETIME"`
		- `eventInfo`: `"string"`

### Endpoints:

#### 1. Save new info into event:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}`
-   **Method:** *POST*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-   **Request Payload:**
    
```json
    {
	  "eventInfo": "string"
    }
```
-   **Response:**
    
```json
    {
      "status": "success",
      "message": "Event information saved successfully."
    }
```

#### 2. Edit info of event:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}`
-   **Method:** *PUT*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-   **Request Payload:**
    
```json
	{
      "eventInfo": "string"
    } 
```
-   **Response:**
    
```json
    {
      "status": "success",
      "old_eventInfo": "string"
      "new_eventInfo": "string"
      "message": "Event information updated successfully."
    }
```

#### 3. Delete info of event:

-   **Endpoint:**`/v2/schedule/groups/{groupId}/eventInfo/{event_id}`
-   **Method:** *DELETE*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-   **Response:**
    
```json
    {
      "status": "success",
      "eventId": "event_id"
      "message": "Event information deleted successfully."
    }
```
    

#### 4. Show list of events for today:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}/day`
-   **Method:** *GET*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-    **Query Parameters:**
		-  `userId`: User ID
	    -  `day`: number
-   **Response:**
```json
    {
      "events": [
        {
          "eventId": "event_id",
          "disciplineId": "discipline_id",
          "disciplineType": "LECTURE|LAB|PRACTICE"
          "start_time": "DD.MM.YY.hh:mm",
          "end_time": "DD.MM.YY.hh:mm",
          "event_info": "string"
        },
        // Other events for today
      ]
    }
```
    

#### 5. Show list of events for next day:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}/day`
-   **Method:** *GET*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-    **Query Parameters:**
		-  `userId`: User ID
	    -  `day`: number
-   **Response:**
```json
    {
      "events": [
        {
          "eventId": "event_id",
          "disciplineId": "discipline_id",
          "disciplineType": "LECTURE|LAB|PRACTICE"
          "start_time": "DD.MM.YY.hh:mm",
          "end_time": "DD.MM.YY.hh:mm",
          "event_info": "string"
        },
        // Other events for today
      ]
    }
```
    

#### 6. Show list of events for current week:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}/week`
-   **Method:** *GET*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-    **Query Parameters:**
		-  `userId`: User ID
	    -  `week`: number
-   **Response:**
```json
    {
      "events": [
        {
          "eventId": "event_id",
          "disciplineId": "discipline_id",
          "disciplineType": "LECTURE|LAB|PRACTICE"
          "start_time": "DD.MM.YY.hh:mm",
          "end_time": "DD.MM.YY.hh:mm",
          "event_info": "string"
        },
        // Other events for today
      ]
    }
```
    

#### 7. Show list of events for next week:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}/week`
-   **Method:** *GET*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-    **Query Parameters:**
		-  `userId`: User ID
	    -  `week`: number
-   **Response:**
```json
    {
      "events": [
        {
          "eventId": "event_id",
          "disciplineId": "discipline_id",
          "disciplineType": "LECTURE|LAB|PRACTICE"
          "start_time": "DD.MM.YY.hh:mm",
          "end_time": "DD.MM.YY.hh:mm",
          "event_info": "string"
        },
        // Other events for today
      ]
    }
```

#### 8. Show list of events for exact lesson's event sequence:

-   **Endpoint:** `/v2/schedule/groups/{groupId}/eventInfo/{event_id}`
-   **Method:** *GET*
-    **Path Parameters:**
		-  `groupId`: Group ID
	    -  `event_id`: Event ID
-    **Query Parameters:**
		-  `userId`: User ID
-   **Response:**
```json
    {
      "events": [
        {
          "eventId": "event_id",
          "disciplineId": "discipline_id",
          "disciplineType": "LECTURE|LAB|PRACTICE"
          "start_time": "DD.MM.YY.hh:mm",
          "end_time": "DD.MM.YY.hh:mm",
          "event_info": "string"
        },
        // Other events for today
      ]
    }
```
