### ISSUE TITLE
Research on /enable command in DM

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor-bot#138]
We need to create an ability to take enable notifications about future pair in DM with the help of /command.

The functionality of this command is the same as /enable in group chat

Your task is to research back-end application of FA with the purpose to find endpoints or tables in database that is necessary for proper work of poll in telegram **but missing**. You need to describe:
- in endpoints:
  - path of endpoint
  - http method (get, post, etc.)
  - params in endpoint path
  - query parameters (params after ? in request path)
  - request body (if necessary)
  - response body (if necessary)
- in tables of database:
  - fields
  - types
  - relations
  - uniqueness
  - default values

Be very accurate and responsible for what you write. Check twice all that you found and described to find mistakes and fix it in time

**Comment by iamthegoose** [comment]
## We have two solutions for the implementation this functionality:
---
### **1. Adding a new field to an already existing `Students` table:**
```json
{
    //other fields of table Students
    "notification": "boolean"
}
```
#### Endpoint
- **Path**: `/v2/students/{studentId}`
- **Method**: _PATCH_
- **Path parameters**:
    - `studentId`: Student ID
- **Response**:
```json
{
    "status": "string",
    "notification": "boolean",
    "message": "string"
}
```
### **2. Creating a new table with Students, that want to get notifications**
```json
{
    "student": "Student"
}
```
#### Endpoint 1
- **Path**: `/v2/notifications/{studentId}`
- **Method**: _PATCH_
- **Path parameters**:
    - `studentId`: Student ID
- **Response**:
```json
{
    "status": "string",
    "message": "string"
}
```
#### Endpoint 2
- **Path**: `/v2/notifications/`
- **Method**: _GET_
- **Response**:
```json
{
    "students": {
        "Student",
        "Student",
        //other Student type objects
    }
}
```
